[project]
name = "common-crud"
version = "0.1.3"
description = "Common CRUD operations for SQLAlchemy and FastAPI"
authors = [
    {name = "smdsu",email = "109036946+smdsu@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sqlalchemy (>=2.0.40,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
aiosqlite = "^0.21.0"
pytest-asyncio = "^0.26.0"
pytest-cov = "^6.1.1"

[tool.setuptools.package-data]
common_crud = ["py.typed"]

