[project]
name = "tagwriting"
version = "0.3.1.5"
description = "A CLI tool for tag-based text processing."
authors = [
    { name = "esehara", email = "esehara@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click",
    "rich",
    "readchar",
    "watchdog",
    "python-dotenv",
    "pyyaml",
    "requests",
    "beautifulsoup4"
]
classifiers = [ 
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", 
]

[project.scripts]
tagwriting = "tagwriting.main:main"

[tool.setuptools]
packages = ["tagwriting"]

[project.urls]
GitHub = "https://github.com/esehara/tagwriting"