[project]
name = "AreYouHumanLib"
version = "0.1.7.1"
authors = [
    {name = "Andrzej", email = "andrzej.krajnow1337@gmail.com"},
]
description = "."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "emoji_data_python>=1.6.0",
    "alive-progress>=3.2.0",
    "requests>=2.32.0",
    "aiogram>=3.18.0",
    "pillow>=11.2.1",
    "click>=8.1.8",
    "numpy>=2.2.4",
]

[build-system]
requires = ["setuptools>=78.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[project.scripts]
areyouhuman = "AreYouHuman.cli:cli"
