[project]
name = "model-mocker"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "Paul", email = "paulotto.bethge@gmail.com" },
]
dependencies = [
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "Faker>=37.1.0",
    "pytest-asyncio>=0.26.0",
]
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
