[project]
name = "pydantic_encryption"
version = "0.0.2a2"
description = "Encryption and hashing models for Pydantic"
authors = [
    { name = "Julien Kmec", email = "me@julien.dev" },
]
readme = "README.md"
packages = [{include = "pydantic_encryption"}]
requires-python = ">=3.9,<4.0.0"
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.9.1",
    "bcrypt (>=4.3.0,<5.0.0)",
]

[project.optional-dependencies]
evervault = ["evervault>=4.4.1"]
generics = ["python-generics>=0.2.3"]
test = ["pytest>=8.3.5", "coverage>=7.8.0"]
all = ["evervault>=4.4.1", "python-generics>=0.2.3", "pytest>=8.3.5", "coverage>=7.8.0"]

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"
