[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "che168"
version = "1.0.3"
description = "Official Python client parser for the Carapis Che168 API. Access real-time vehicle data via a powerful REST API. (Che168)"
authors = ["Carapis.com <info@carapis.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://carapis.com/"
repository = "https://github.com/markolofsen/carapis-che168-pypi"
documentation = "https://carapis.com/docs"
keywords = ["che168", "che168_api", "carapis", "car_data", "vehicle_data", "used_car_api", "client", "parser", "automotive", "Che168"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "src/che168/*.py",
    "LICENSE",
    "README.md"
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = "^2.31.0"
pyyaml = "^6.0.1"
python-dotenv = "^1.0.0"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
