[project]
name = "lsoph"
description = "An interactive lsof alternative"
version = "0.0.3"
authors = [
    { name = "Gareth Davidson", email = "gaz@bitplane.net" }
]
readme = "README.md"
requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Public Domain", # WTFPL
    "Operating System :: POSIX :: Linux",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "psutil~=7.0",
    "textual~=3.1"
]

[project.optional-dependencies]
dev = [
    "flake8",
    "pre-commit",
    "pytest",
    "coverage",
    "pytest-cov",
    "build",
    "twine",
    "pydoc-markdown"
]

[project.urls]
"Homepage" = "https://bitplane.net/dev/python/lsoph"
"Source Code" = "https://github.com/bitplane/lsoph"
"Bug Tracker" = "https://github.com/bitplane/lsoph/issues"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project.scripts]
lsoph = "lsoph.cli:main"

[tool.isort]
profile = "black"

