[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vcsvgenie"
version = "2.2.6"
description = "Programmatic Interpretations of Cadence Virtuoso Waveform VCSV files"
authors = [
    {name = "Jake Peterson", email = "jake612@duck.com"}
]
readme="README.md"
dependencies = [
    "numpy>=2.0.0, <3.0.0", # widened for colab support
    "matplotlib>=3.9.0,<4.0.0",
    "pandas>=2.2.0,<3.0.0",
    "scikit-learn>=1.5.0,<2.0.0",
    "sortedcontainers>=2.4.0,<3.0.0",
]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/fsharp4/vcsvgenie"
Issues = "https://github.com/fsharp4/vcsvgenie/issues"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "jupyter",
    "notebook",
    "ipython",
    "tqdm>=4.66.0"
]

[tool.setuptools]
packages = ["vcsvgenie"]

[tool.poetry.group.dev.dependencies]
twine = "^6.1.0"

