[tool.poetry]
name    = "satcube"
version = "0.1.13"
description = "A Python package to create cloud-free monthly composites by fusing Landsat and Sentinel-2 data."
authors = ["Cesar Aybar <fcesar.aybar@uv.es>"]
repository     = "https://github.com/IPL-UV/satcube"
documentation  = "https://ipl-uv.github.io/satcube/"
readme         = "README.md"
packages       = [{ include = "satcube" }]

[tool.poetry.dependencies]
python          = ">=3.10,<4.0"
cubexpress      = ">=0.1.7"
mlstac          = ">=0.4.0"
satalign        = ">=0.1.11"         
segmentation-models-pytorch = ">=0.3.0"
scikit-learn    = ">=1.2.0"
pandas          = ">=2.0.0"
pydantic        = ">=2.8.0"
rasterio          = ">=1.3.9"  
earthengine-api   = ">=1.5.12"  
numpy           = ">=1.25.0"
requests        = ">=2.26.0"
xarray          = ">=2023.7.0"
utm             = ">=0.7.0"   
phicloudmask    = ">=0.0.2" 

[tool.poetry.extras]
full = ["torch"]

# --- tooling fixes ----------------------------------------------------------
[tool.mypy]
files                   = ["satcube"]
disallow_untyped_defs   = true
disallow_any_unimported = true
no_implicit_optional    = true
check_untyped_defs      = true
warn_return_any         = true
warn_unused_ignores     = true
show_error_codes        = true

[tool.ruff]
target-version = "py310"
line-length    = 120
fix            = true
select         = ["YTT","S","B","A","C4","T10","SIM","I","C90","E","W","F","PGH","UP","RUF","TRY"]
ignore         = ["E501","E731"]
