[tool.poetry]
name = "sag-py-web-common"
version = "1.0.3"
description = "Small helper functions for web projects"
authors = ["Samhammer AG"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
asgi-logger = "^0.1.0"
fastapi = "^0.110.3"

[tool.poetry.group.dev.dependencies]
anyio = ">=4.4.0"
build = ">=1.1.1"
coverage-lcov = "*"
flake8 = ">=5.0.4"
httpx = "*"
mock = "*"
mypy = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
toml = "*"
types-mock = "*"
zipp = ">=3.19.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
