[project]
name = "salute"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "twine>=6.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
