[project]
name = "XML2DCM-ECG"
version = "1.1.0"
description = "Python-based solution for converting ECG data from XML format to the DICOM(Digital Imaging and Communications in Medicine) format"
readme = "README_PYPI.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{name = "eunbyul", email = "eunbyul616@gmail.com"}]
dependencies = ['numpy', 'tqdm', 'pydicom==2.4.4']

[tool.uv.workspace]
members = [
    "XML2DCM-ECG",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["xml2dicom"]

[project.scripts]
xml2dicom = "xml2dicom.main:main"