[project]
name = "amuesm"
version = "2.4"
description = "A module used to create random passwords with customizable options and to encode/decode strings!"
authors = [{name="Annie"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=2.6"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
