[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "identitwin"
version = "0.0.49"
description = "A Tool to setup a Raspberri Pi for Structural Health Monitoring accelerations and displacements"
authors = [
    { name = "Angel Navarro-Mora", email = "ahnavarro@itcr.ac.cr" },
    { name = "Alvaro Perez-Mora", email = "alvaroenrique2001@estudiantec.cr" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=2.2.5",                    
    "matplotlib>=3.10.1",              
    "gpiozero>=2.0.1",                 
    "adafruit-circuitpython-ads1x15>=2.4.2",
    "mpu6050-raspberrypi>=1.2",
    "RPi.GPIO>=0.7.1",                 
    "Adafruit-Blinka>=8.56.0",         
    "adafruit-circuitpython-busdevice>=5.2.11",
    "adafruit-circuitpython-register>=1.10.2",
    "Adafruit-PlatformDetect>=3.77.0", 
    "Adafruit-PureIO>=1.1.11",         
    "lgpio>=0.2.2.0",                  
    "smbus>=1.1.post2",
    "pyserial>=3.5",
    "pandas>=2.2.3",
    "scipy>=1.12.0",  # Added for better signal filtering capabilities
]

[tool.setuptools]
packages = ["identitwin"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
identitwin = ["tests/*.py"]