[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GamaWu"
version = "0.1.0"
description = "A simple hello world package"
authors = [{ name = "Gama", email = "wumian1996@gmail.com" }]
readme = "README.md"
requires-python = ">=3.7"
