[project]
name = "smolcrawl"
version = "0.1.0"
authors = [
  { name="Bill Chambers", email="contact@learnbybuilding.ai" },
]
description = "Crawls and indexes websites"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
# license-files = ["LICEN[CS]E*"] # No license file

[project.urls]
Homepage = "https://github.com/bllchmbrs/smolcrawl"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
dependencies = [
    "crawlee[all]>=0.6.7",
    "diskcache>=5.6.3",
    "loguru>=0.7.3",
    "markdownify>=1.1.0",
    "python-dotenv>=1.1.0",
    "readabilipy>=0.3.0",
    "rich>=14.0.0",
    "tantivy>=0.22.2",
    "typer>=0.15.2",
]

[dependency-groups]
build = [
    "twine>=6.1.0",
]

[project.scripts]
smolcrawl = "smolcrawl:app"
