[project]
name = "pydantic_encryption"
version = "0.0.2a8"
description = "Encryption and hashing models for Pydantic"
authors = [
    { name = "Julien Kmec", email = "me@julien.dev" },
]
readme = "README.md"
packages = [{include = "pydantic_encryption"}]
requires-python = ">=3.10,<4.0.0"
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.9.1",
    "bcrypt (>=4.3.0,<5.0.0)",
    "evervault>=4.4.1",
    "sqlalchemy (>=2.0.40,<3.0.0)",
    "boto3 (>=1.38.3,<2.0.0)"
]

[project.optional-dependencies]
generics = ["python-generics>=0.2.3"]
test = ["pytest>=8.3.5", "coverage>=7.8.0", "pytest-env (>=1.1.5,<2.0.0)"]
all = ["python-generics>=0.2.3", "pytest>=8.3.5", "coverage>=7.8.0", "pytest-env (>=1.1.5,<2.0.0)"]

[tool.pytest_env]
ENCRYPTION_KEY = "FF9OqqsxdRoge7b0orbJ7EZAn96bLFDgoa8icBF3GNM="

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"
