[project]
name = "hello-proj"
version = "0.1.2-4"
description = "Something"
authors = [{ name = "AmirthanathanR", email = "amirth300324@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["django (>=5.2,<6.0)", "gunicorn (>=23.0.0,<24.0.0)"]

[project.scripts]
main = "hello_proj:main"

manage = "django.core.management:execute_from_command_line"

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.11.7"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
