
[project]
name = "random-insertion"
version = "0.3.0a2"
description = "A library for performing fast random insertion on TSP and SHPP instances"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
license = { text = "Apache-2.0 license" }
authors = [{ name = "Furffico" }]
dependencies = ["numpy>=1.21"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Utilities",
]

[project.urls]
Repository = "https://github.com/Furffico/random-insertion"
Issues = "https://github.com/Furffico/random-insertion/issues"

[build-system]
requires = ["setuptools>=50.0", "numpy>=1.21"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false
packages = ["random_insertion"]

[tool.cibuildwheel]
build = "cp3{7,8,9,10,11,12,13}-{manylinux_x86_64,win_amd64}"
skip = "cp36-*"

test-requires = ["pytest"]
test-command = "pytest {project}/tests"
