[project]
name = "mkdocs-fun-plugin"
version = "0.1.0"
description = "Dead simple custom python functions with mkdocs"
readme = "README.md"
authors = [
  { name = "Guðmundur Björn Birkisson", email = "gbb@gbb.is" },
]
requires-python = ">=3.9"
dependencies = [
  "mkdocs>=1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "pyright==1.1.400",
  "pytest-cov==6.1.1",
  "ruff==0.11.6",
]

[project.entry-points."mkdocs.plugins"]
fun = "mkdocs_fun_plugin.plugin:FunPlugin"

[tool.ruff]
line-length = 96

[tool.ruff.lint]
select = [
  "ALL",
]
ignore = [
  "C901",
  "D",
  "PLR0912",
  "PT009",
  "PT027",
  "S101",
  "SLF001",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
addopts = "--cov=mkdocs_fun_plugin --cov-report xml"
