[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qd2_controller"
version = "1.1.1"
description = "Software for Quditto controller"
authors = [ { name="Javier Perez", email="javier.perez@imdea.org"}, {name="Blanca Lopez", email="blanca.lopez@imdea.org"}, {name="Angela Diaz", email="angela.diaz@imdea.org"},]
requires-python = ">=3.8"
dependencies = [ 
    "netsquid",
    "pika ~=1.3.2",
    "aio_pika ~= 9.5.5",
    "uvicorn ~= 0.34.0",
    "fastapi ~= 0.115.11",
]