[project]
name = "mcp-server-weather"
version = "0.1.4"
description = "输入OpenWeather-API-KEY，获取天气信息。"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.6.0",
]
[project.scripts]
mcp-server-weather = "main:main"