[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-axe"
version = "0.1.1"
description = "MCP plugin for accessibility testing using Axe-core"
authors = [
    { name="Manoj Kumar", email="your-email@example.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

dependencies = [
    "typer>=0.9.0",
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.22.0",
    "selenium>=4.10.0",
    "playwright>=1.44.0",
    "pyyaml>=6.0",
    "toml>=0.10.2",
    "requests>=2.28.0",
    "mcp>=1.6.0"
]
[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
    "pytest-asyncio"
]

[project.scripts]
mcp-axe = "mcp_axe.cli:app"


[tool.setuptools]
packages = ["mcp_axe"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"mcp_axe" = ["static/axe.min.js"]