[project]
name = "khashimoto-echo-dt"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "K hashimoto", email = "keishi04hrikzira@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["typer>=0.15.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
khashimoto_echo_dt = "khashimoto_echo_dt.__main__:main"
