# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
[tool.poetry]
name = "FastRAMQPI"
version = "10.4.1"
description = "Rammearkitektur integrations framework"
authors = ["Magenta ApS <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/FastRAMQPI"
keywords = ["os2mo"]
packages = [ { include = "fastramqpi" } ]
include = ["fastramqpi/py.typed"]

[tool.poetry.dependencies]
python = "^3.11"
structlog = ">=24,<26"
pydantic = "^1"
gql = "^3"
more-itertools = ">=9,<11"
prometheus-fastapi-instrumentator = "^7"
fastapi = "^0.115"
starlette = "^0.41"
httpx = "^0.27"
pytest = "^8"
respx = ">=0.21,<0.23"
tenacity = ">=8,<10"
tqdm = "^4"
Authlib = "^1"
aio-pika = "^9"
aiormq = "^6"
prometheus-client = "^0.20"
anyio = "^3"
Jinja2 = "^3"
requests = "^2"
sentry-sdk = "^1"
frozendict = "^2"
sqlalchemy = "^2"
psycopg = "^3"
debugpy = "^1"
hypothesis = "^6"
click = "^8"
aiohttp = "^3"
ariadne-codegen = "0.7.1"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.24"
pytest-split = "^0.9"
pytest-cov = "^5"
pytest-mock = "^3"
pytest-aiohttp = "^1"

[tool.poetry.group.pre-commit.dependencies]
pre-commit = "^3"
ruff = "^0.9"
deptry = "^0.23"
mypy = "^1"
types-pyyaml = "^6"
types-tqdm = "^4"
types-requests = "^2"

[tool.poetry.plugins."pytest11"]
fastramqpi = "fastramqpi.pytest_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.mypy]
python_version = "3.11"
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"
plugins = "pydantic.mypy"

[[tool.mypy.overrides]]
# The module seems to be missing library stubs or py.typed marker
module = "authlib.*"
ignore_missing_imports = true

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = [
    # isort
    "I"
]
ignore = [
  # Allow function calls in arguments, like `Depends(...)`
  "B008",
  # Allow lines longer than 90 characters if ruff-format decides so
  "E501"
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.coverage.run]
omit = [
    # The pytest plugin is tested implictly through the integration tests
    "fastramqpi/pytest_plugin.py",
]

[tool.deptry.package_module_name_map]
gql = "graphql"
[tool.deptry.per_rule_ignores]
DEP002 = [
  # psycopg is used by sqlalchemy
  "psycopg",
]
