[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "url2llm"
version = "0.1.0"
description = "The easiest way to crawl a website and produce LLM ready markdown files"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.5.0.post8",
    "fire>=0.7.0",
]

[project.scripts]
url2llm = "url2llm.cli:url2llm"

[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/diegobit/url2llm"

