[build-system]
requires = ["setuptools<68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CHM"
version = "1.4.2"
authors = [
    {name="Chris Marsh"}
]
description = "python tools for CHM"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ['vtk', 'numpy', 'xarray', 'netCDF4', 'pandas',
                'gdal', 'dask[complete]',
                'pyvista>0.29', 'rioxarray', 'rasterio', 'ninja', 'cftime', 'pyproj']


[project.urls]
Homepage = "https://github.com/Chrismarsh/mesher"

[project.scripts]
pvdFromDir = "CHM.tools.pvd_from_dir:main"
validateJSON = "CHM.tools.validate_json:main"
windmapper2mesher = "CHM.tools.windmapper2mesher:main"
vtu2geo = "CHM.tools.vtu2geo:main"

