[project]
name = "ashredis"
version = "1.0.2"
description = "Async Redis ORM for Python"
readme = "README.md"
authors = [{name = "Bloodycat", email = "mrblooddycat@gmail.com"}]
keywords = ["redis", "orm", "async", "asyncio", "hash"]
dependencies = [
    "redis >=5.0.8",
]
requires-python = ">=3.8"