[project]
name = "ragstax"
version = "0.1.0"
description = "RAG pipelines"
authors = [{ name = "Rishabh Deshpande", email = "rishabh9to5@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "transformers",
    "nltk"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
