[project]
name = "walnut-cli"
version = "0.7"
description = "Walnut + Jupyter packaged as a Python client"
readme = "README.md"
authors = [
    { name = "Nicolas Ollinger", email = "nopid@free.fr" }
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.1.0",
    "jdk4py>=21.0.4.2",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "pydot>=3.0.4",
    "walnut-kernel>=0.3.3",
]

[project.optional-dependencies]
render = [
    "quarto-cli>=1.6.42"
]

[project.urls]
Homepage = "https://github.com/nopid/walnut_cli"

[project.scripts]
walnut = "walnut_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


