[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "ntsulib"
version = "1.2.219"
authors = [
    { name = "NTsukine", email = "398339897@qq.com" }
]
description = "ntsulib"
dependencies = ['certifi==2025.1.31', 'chardet==5.2.0', 'charset-normalizer==3.4.1', 'idna==3.10', 'psycopg2==2.9.10', 'PyQt5==5.15.11', 'PyQt5-Qt5==5.15.2', 'PyQt5_sip==12.17.0', 'python-a2s==1.4.1', 'requests==2.32.3', 'urllib3==2.4.0']
